### ISSUE TITLE
Version 3.0.1: exec user process caused: exec format error

### ISSUE THREAD

**Issue by Killerjoe** [jokay/docker-ccu-historian#179]
Hi,

I wanted to upgrade from 2.8.3 to 3.0.1 and as I was trying to start up my docker-compse.yml file, I get the following issue:

```/usr/bin/python3 /usr/bin/docker-compose -f docker-compose.yml up   
Starting ccu-historian_app_1 ... done  
Attaching to ccu-historian_app_1  
app_1  | standard_init_linux.go:228: exec user process caused: exec format error  
ccu-historian_app_1 exited with code 1
```

I was able to upgrade to 2.9.0 without issues.
I use docker-ccu-historian on a Raspberry Pi 4 with Ubuntu 21.10.

```uname -a
Linux pyfhem1 5.13.0-1024-raspi #26-Ubuntu SMP PREEMPT Fri Mar 25 10:54:36 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux  
more /etc/issue
Ubuntu 21.10 \n \l
```

Thank you,
Regards,
Jochen

**Comment by jokay** [comment]
@Killerjoe thank you for using the **Bug report** template when creating a new issue for a bug next time. I will investigate this.

**Comment by jokay** [comment]
Please provide the following information:

**Environment (please complete the following information):**

- Docker version [e.g. 20.10.3]
- Docker compose version [e.g. 1.28.2]

**Command used to run the container**

- [e.g. docker run -v ...]

**Docker compose file (with passwords redacted)**

```yml
services:
   image: ...
```

**Comment by Killerjoe** [comment]
Hi jokay,

I will use the template next time. I was not aware of it.

Here you will find the requested information:

```
jochen@pyfhem1:~$ docker -v
Docker version 20.10.7, build 20.10.7-0ubuntu5.1
jochen@pyfhem1:~$ docker-compose -v
docker-compose version 1.27.4, build unknown
```

Command to start the docker-compose file:

```
/usr/bin/python3 /usr/bin/docker-compose -f docker-compose.yml up
```

```
jochen@pyfhem1:~$ more /var/lib/ccu-historian/docker-compose.yml
version: "3"
services:
  app:
    image: docker.io/xjokay/ccu-historian:latest
    volumes:
      - ./data/database:/database
      - ./data/config:/opt/ccu-historian/config
    ports:
      - 8080:80
      - 2098:2098
      - 2099:2099
      - 8082:8082
      - 9092:9092
      - 5435:5435
    environment:
      - TZ=Europe/Berlin
      - CONFIG_CCU_TYPE=CCU3
      - CONFIG_CCU_IP=192.168.xxx.xxx
      - CONFIG_HOST_IP=192.168.xxx.xxx
      - CONFIG_HOST_BINRPCPORT=2099
      - CONFIG_HOST_XMLRPCPORT=2098
    networks:
      - default
jochen@pyfhem1:~$

```


Regards,
Jochen
